### ISSUE TITLE
Possible simplification

### ISSUE THREAD

**Issue by idevtier** [derektata/wrap-toggle.nvim#1]
I was looking for a simple solution for wrapping text and found this plugin. After looking at the code, I decided to simplify it. I got the following solution:

```lua
function Toggle_wrap()
  vim.cmd [[ set wrap! ]]
  vim.cmd [[ set linebreak! ]]
end
```

What do you think?

**Comment by derektata** [comment]
I just saw this a little while ago, and updated the simplicity of my script. I also added the ability to change the key bind in your config if you choose to do so.

The way my script is written, it's using Neovim's native API's versus vim commands.

**Comment by Letsric** [comment]
You can get the functionality of this plugin with just 3 lines of `init.lua`:
```lua
vim.opt.linebreak = true
vim.opt.wrap = false
vim.keymap.set("n", "<A-z>", function() vim.opt.wrap = not vim.opt.wrap:get() end)
```
